baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Paintsville Utilities"

[params]
    Id = "paintsvilleutilities"
    Color = "#1b72e8"
    AppTitle = "PU Advisory"
    Description = "Alerts and interactive map to serve the customers of Paintsville Utilities"
    Facebook = ""
    BillPay = "https://paintsvilleutilities.epayub.com/Account/Login?ReturnUrl=%2F"

[blackfriday]
    extensions = ["hardLineBreak"]

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
